### ISSUE TITLE
Using scheduling objects and parallelise simmer runs

### ISSUE THREAD

**Issue by DirkEngelen** [r-simmer/simmer#259]
Sorry I am new user of simmer so perhaps I implemented it wrong, but I face some problems between scheduling objects and parallelise simmer runs.

When trying to make replications (parallelise via mclapply) in simmer using resources that have a scheduling object set as capacity, it is not continuing after the first run (see below error message). When removing the scheduling object and setting capacity to 1 for example, parallelisation is working properly (but gives wrong results obviously).

The error message:
"Error: resource 'Delivery team' was defined, but no schedule was attached "
Although the resource is defined by:
"add_resource("Delivery team", capacity = delivery_all_schedule, queue_size = Inf, mon = TRUE)"

Is this a known issue or how can I solve this?
Thank you,
Dirk

**Comment by Enchufa2** [comment]
This is because you are not including the `simmer()` call into your chunk that is being parallelized, and as a result you are defining your resources multiple times. Take a look at [this thread](https://groups.google.com/g/simmer-devel/c/DFAXdkP2c2U/m/s7t0bQFxBAAJ). Also, more hints on parallelization can be found [here](https://github.com/r-simmer/simmer/discussions/244).

Closing this, as this is not a simmer issue. Please, consider responding to the thread above if you have further questions, or, if you are more comfortable on GitHub, consider opening a new question under the _Discussions_ tab.
