### ISSUE TITLE
Problem with dev tidyr

### ISSUE THREAD

**Issue by hadley** [r-simmer/simmer#40]
I see:

```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:

  2. Failure (at test-simulation-1.R#37): a simple deterministic simulation with rejections behaves as expected 
  mean(resources$server) not equal to 2/3
  0.662 - 0.667 == -0.00442

  Trajectory: anonymous, 1 activities
  testthat results ================================================================
  OK: 178 SKIPPED: 0 FAILED: 2
  1. Failure (at test-simulation-1.R#35): a simple deterministic simulation with rejections behaves as expected 
  2. Failure (at test-simulation-1.R#37): a simple deterministic simulation with rejections behaves as expected 

  Error: testthat unit tests failed
  Execution halted
```

Could you please let me know if this is a new bug in tidyr?

**Comment by Enchufa2** [comment]
Thanks for the report. It has nothing to do with tidyr. This is [the same error that the CRAN reports](https://cran.rstudio.com/web/checks/check_results_simmer.html) with clang, but I am unable to reproduce it (although I use clang too...). I think the cause is not a bug but a weak test design, and the development version should pass the check in all platforms, but I cannot be entirely sure. It would help if you can give us more details about your testing environment.

**Comment by Enchufa2** [comment]
The problem is definitely solved in the current release.
