### ISSUE TITLE
Try to use magrittr's `%>%` instead of `$` for chaining

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#6]
The operator `$` accesses R6 classes' methods and attributes. The only solution I can glimpse right now is to mask `$` with `%>%`, but this makes magrittr's original `%>%` unusable, which is self-defeating.

Other ideas are welcome. Until then, R users must get accustomed to `$`. ¯_(ツ)_/¯

**Comment by bart6114** [comment]
If we want this, we will have to create some minimal 'dummy' functions. Consider the example below.

```
library(R6)

testClass<-
  R6Class("test",
          public=list(
            bar=c(),
            foo=function(value){
              self$bar<-c(self$bar, value)
              invisible(self)
            }
          )
  )

test<-function() testClass$new()
foo<-function(test_instance, value) test_instance$foo(value)
bar<-function(test_instance) test_instance$bar

library(magrittr) # should be imported automatically upon loading package

test() %>%
  foo(1) %>%
  foo(2) %>%
  foo(3) %>%
  bar()

[1] 1 2 3
```

While it doesn't improve function **at all**, I believe it does improve usability as the average R user IMO is much more familiar with the `%>%` syntax. Therefor, it's a nicety but not a priority. 

As a side note, if we ever step away from the R6 approach, it think it will be (relatively) easier to maintain a steady syntax using `%>%` instead of when using `$`.

**Comment by Enchufa2** [comment]
Mmh... interesting. I'll postpone the submission to CRAN in order to take a look at this. :-)

**Comment by Enchufa2** [comment]
Done! Thanks for your feedback!
