### ISSUE TITLE
Bank event simulation

### ISSUE THREAD

**Issue by bmanjare** [r-simmer/simmer#89]
Hi,
I am new at everything, including R, and this is my first comment at github. So kindly forgive if this is not a right platform to raise query like this.

I am trying to implement following example:
Consider a system of two servers where customers from outside the system arrive at server 1 at a Poisson rate 4 and at server 2 at a Poisson rate 5. The service rates of 1 and 2 are respectively 8 and 10. A customer upon completion of service at server 1 is equally likely to go to server 2 or to leave the
system (i.e., P11 = 0, P12 = 12 ); whereas a departure from server 2 will go 25 percent of the time to server 1 and will depart the system otherwise (i.e., P21 = 14 , P22 = 0).
Code ref: http://r-simmer.org/articles/D-bank-1.html

I used cumsum(rexp()) for poisson. But in creating env bank not sure how to use the same. Please let me know what changes are necessary to implement above requirement.

```r
library(dplyr)
library(simmer)

set.seed(1554)

loop <- function(...) {
  time_diffs <- c(...)
  i <- 0
  function() {        
    if (i < length(time_diffs)) {     
      i <<- i+1       
    } else {      
      i <<- 1     
    }     
    return(time_diffs[i])     
  }       
}

lambda1 <- 4
mu1 <- 8
lambda2 <- 5
mu2 <- 10


customer <- 
  trajectory("Customer's path") %>%
  select(c("counter1", "counter2"),"round-robin") %>%
  seize_selected(amount = 1) %>%
  #seize_selected("counter1") %>%
  timeout(function() {cumsum(rexp(1, 1/mu1))}) %>% #Service poisson
  #release("counter1") %>%
  release_selected(amount = 1) %>%
  leave(prob = 0.5) %>%
  #seize("counter2") %>%
  seize_selected(amount = 1) %>%
  timeout(function() {cumsum(rexp(1, 1/mu2))}) %>% #Service poisson
  #release("counter2") %>%
  release_selected(amount = 1) %>%
  leave(prob = 0.25)

bank <- 
  simmer("bank") %>% 
  add_resource("counter1", capacity = 1, queue_size =1) %>%
  add_resource("counter2", capacity = 1, queue_size =1) %>%
  add_generator("Customer", customer, function() {c(0, cumsum(rexp(10, 1/lambda1))*cumsum(rexp(10, 1/lambda2)), -1)})

bank %>% run(until = 1000) 

get_mon_arrivals(bank)
get_mon_resources(bank)
```

**Comment by Enchufa2** [comment]
Welcome to R, simmer and GitHub then. :) General comments:

1. On how to post on GitHub with Markdown, including how to format code chunks, see [this guide](https://guides.github.com/features/mastering-markdown/) (I have already edited your comment to correctly format the code).
2. Our [mailing list](https://groups.google.com/forum/#!forum/simmer-devel) is a better place to raise this kind of question. Please, consider subscribing to post future questions there.

About your simulation:

1. In R, there is `rpois()`, that generates a Poisson distribution.
2. The cumulative sum of an exponential distribution is *not* a Poisson distribution.
3. A Poisson distribution is discrete, and it is generally used for counting processes. So it is pretty artificial to select it as an interarrival distribution.
4. What I suppose then is that you want to use a *Poisson process*, which is not the same as a Poisson distribution. Please, take a look at [this document](http://www.it.uc3m.es/iucar/tr/02-R-en.html#poisson-processes) for more details. As you will see there, the interarrival times of a Poisson process follow an exponential distribution. You need to specify interarrival times in *simmer*, so you may want to use just `rexp()`.
5. You are describing basically a loop, because a customer *could* be there alternating between counters indefinitely. There should be a `rollback()` somewhere.
6. I would store the current counter as an attribute and describe the trajectory in *one* generic counter based on that attribute, with a `rollback()` at the end.
7. Finally, you know the arrival distribution for each counter, so it is easier and faster to specify two different points of attachment to the main trajectory.

The code:

```r
library(simmer)

set.seed(1554)

lambda <- c(4, 5)
mu <- c(8, 10)
leave_prob <- c(0.5, 0.75)

change_counter <- function(attr) {
  i <- attr["counter"] + 1
  if (i > 2) i <- 1
  i
}

customer <- trajectory() %>%
  select(function(attr) paste0("counter", attr["counter"])) %>%
  seize_selected(amount = 1) %>%
  timeout(function(attr) rexp(1, 1/mu[attr["counter"]])) %>%
  release_selected(amount = 1) %>%
  leave(function(attr) leave_prob[attr["counter"]]) %>%
  set_attribute("counter", change_counter) %>%
  rollback(6, Inf)

counter1 <- trajectory() %>%
  set_attribute("counter", 1) %>%
  join(customer)

counter2 <- trajectory() %>%
  set_attribute("counter", 2) %>%
  join(customer)

bank <- simmer("bank") %>% 
  add_resource("counter1", capacity = 1, queue_size =1) %>%
  add_resource("counter2", capacity = 1, queue_size =1) %>%
  add_generator("customer1", counter1, function() rexp(10, 1/lambda[1])) %>%
  add_generator("customer2", counter2, function() rexp(10, 1/lambda[2]))

bank %>% run(until = 1000) 

get_mon_arrivals(bank)
get_mon_resources(bank)
```

**Comment by bmanjare** [comment]
Thank you Iñaki. Also, I appreciate your kind guidance on appropriate platform to reach the Simmer community! and of course sharing the guide.

Studying Networks Theory - Lab link of yours. Everything you explained make sense.

Code output (for following line) has a column 'finished', which has most, if not all, values 'FALSE'. Does it mean none of the customers are served?

`get_mon_arrivals(bank)`

**Comment by Enchufa2** [comment]
`finished` is `TRUE` whenever an arrival exhausts a path (there are no more activities ahead). In this case, all should be `FALSE`, because the trajectory is an infinite loop: there is no *end*. Every arrival is dropped because 1) it's rejected while trying to seize a counter, or 2) leaves with some probability. 

If you want to distinguish these two cases in the arrivals' table with a different `finish` value, you have a couple of options though:

- You can define a `reject` trajectory, so that case 1) produces a `TRUE` and 2) still produces a `FALSE`:

```r
customer <- trajectory() %>%
  select(function(attr) paste0("counter", attr["counter"])) %>%
  seize_selected(amount = 1,
                 reject = trajectory() %>% timeout(0)) %>%
  timeout(function(attr) rexp(1, 1/mu[attr["counter"]])) %>%
  release_selected(amount = 1) %>%
  leave(function(attr) leave_prob[attr["counter"]]) %>%
  set_attribute("counter", change_counter) %>%
  rollback(6, Inf)
```

- You can use a `branch()` instead of a `leave()`, so that case 1) still produces a `FALSE` and 2) produces a `TRUE`:

```r
customer <- trajectory() %>%
  select(function(attr) paste0("counter", attr["counter"])) %>%
  seize_selected(amount = 1) %>%
  timeout(function(attr) rexp(1, 1/mu[attr["counter"]])) %>%
  release_selected(amount = 1) %>%
  #leave(function(attr) leave_prob[attr["counter"]]) %>%
  branch(function(attr) runif(1) < leave_prob[attr["counter"]], 
         continue=FALSE,
         trajectory() %>% timeout(0)) %>%
  set_attribute("counter", change_counter) %>%
  rollback(6, Inf)
```

Of course, if you implement both things, then you'll get all `TRUE`.

**Comment by bmanjare** [comment]
That is definitely thought-provoking and resourceful. Thank you once again Iñaki.

There is a bit of change to values of lambda. This example is from the book of S. Ross, Intro to Prob Models.

    rate <- c(4, 5)
    mu <- c(8, 10)
    leave_prob <- c(0.5, 0.75)
    A<-matrix(data=c(1,(-1/4),(-1/2),1), nrow=2, ncol=2, byrow=TRUE);
    b <- matrix(data=c(4,5), nrow=2, ncol=1, byrow=TRUE);
    lambda<-solve(A, b);
    L = ((lambda[1]/(mu[1]-lambda[1]))+(lambda[2]/(mu[2]-lambda[2])))
    cat("L=",L)
    W = L/(rate[1]+rate[2])
    cat("W=",W)

**Comment by Enchufa2** [comment]
Is it the example 8.6, from section 8.4 (page 521 in my edition)? In that example, it says nothing about each counter's queue size, so I suppose they are M/M/1 systems. Therefore, you need to specify infinite queues instead of queues of length 1. Moreover (I didn't realise before), this is not correct: `rexp(10, 1/lambda[1])`, because R expects the rate, not the mean time. If we solve these two errors, you obtain the same results:

```r
library(simmer)

set.seed(1554)

lambda <- c(4, 5)
mu <- c(8, 10)
leave_prob <- c(0.5, 0.75)

change_counter <- function(attr) {
  i <- attr["counter"] + 1
  if (i > 2) i <- 1
  i
}

customer <- trajectory() %>%
  select(function(attr) paste0("counter", attr["counter"])) %>%
  seize_selected(amount = 1) %>%
  timeout(function(attr) rexp(1, mu[attr["counter"]])) %>%
  release_selected(amount = 1) %>%
  leave(function(attr) leave_prob[attr["counter"]]) %>%
  set_attribute("counter", change_counter) %>%
  rollback(6, Inf)

counter1 <- trajectory() %>%
  set_attribute("counter", 1) %>%
  join(customer)

counter2 <- trajectory() %>%
  set_attribute("counter", 2) %>%
  join(customer)

bank <- simmer("bank") %>% 
  add_resource("counter1", capacity = 1, queue_size = Inf) %>%
  add_resource("counter2", capacity = 1, queue_size = Inf) %>%
  add_generator("customer1", counter1, function() rexp(10, lambda[1])) %>%
  add_generator("customer2", counter2, function() rexp(10, lambda[2]))

bank %>% run(until = 1000) 

get_mon_resources(bank) %>%
  dplyr::group_by(resource) %>%
  dplyr::summarise(L = sum(head(system, -1) * diff(time)) / tail(time, 1)) %>%
  dplyr::ungroup() %>%
  dplyr::summarise(L = sum(L))

get_mon_arrivals(bank) %>%
  dplyr::summarise(W = mean(end_time - start_time))
```

**Comment by bmanjare** [comment]
OK, this looks perfect. Updated code at my end with the two suggestions. You have clearly made this great introduction of the Simmer package and an interesting example to learn R for me. Thanks!
